// Generated by CoffeeScript 1.9.3
(function() {
  var videosubApp;

  videosubApp = angular.module('videosubApp', ['ngAnimate', 'ngSanitize', 'yqlService', 'parseService']);

  videosubApp.controller('videosubCtrl', [
    '$scope', '$sce', 'getHTMLwithYQL', 'parsers', function($scope, $sce, getHTMLwithYQL, parsers) {
      var url0, url1, url2, url3, url4;
      $scope.on = true;
      $scope.titleQuery = '';
      $scope.x = 1;
      $scope.y = 0;
      url0 = function(query) {
        return "http://www.springfieldspringfield.co.uk/tv_show_episode_scripts.php?search=" + query;
      };
      url1 = function(query) {
        return "http://tvonline.tw/search.php?key=" + query;
      };
      url2 = function(path) {
        return "http://www.springfieldspringfield.co.uk" + path;
      };
      url3 = function(path) {
        return "http://tvonline.tw/" + path;
      };
      url4 = function(path) {
        return "http://www.springfieldspringfield.co.uk/" + path;
      };
      $scope.searchTitles = function() {
        getHTMLwithYQL(url0($scope.titleQuery)).then(function(html) {
          var items;
          items = parsers.getTitlesFromSpringfield(html);
          $scope.springfieldTitleSuggestions = items;
          return $scope.springfieldTitle = items[0].val;
        });
        return getHTMLwithYQL(url1($scope.titleQuery)).then(function(html) {
          var items;
          items = parsers.getTitlesFromTVOnline(html);
          $scope.tvonlineTitleSuggestions = items;
          return $scope.tvonlineTitle = items[0].val;
        });
      };
      $scope.$watch('springfieldTitle', function(newValue, oldValue) {
        return getHTMLwithYQL(url2(newValue)).then(function(html) {
          var items;
          items = parsers.getEpisodesFromSpringfield(html);
          $scope.springfieldEpisodes = items;
          return $scope.springfieldEpisode = items[0].val;
        });
      });
      $scope.$watch('tvonlineTitle', function(newValue, oldValue) {
        return getHTMLwithYQL(url3(newValue)).then(function(html) {
          var items;
          items = parsers.getEpisodesFromTVOnline(html);
          $scope.tvonlineEpisodes = items;
          return $scope.tvonlineEpisode = items[0].val;
        });
      });
      $scope.$watch('tvonlineEpisode', function(newValue, oldValue) {
        return getHTMLwithYQL(url3(newValue)).then(function(html) {
          var comp, items;
          comp = function(i, j) {
            if (i.name === 'nowvideo' || i.name === 'movshare') {
              return -1;
            } else {
              return 1;
            }
          };
          items = parsers.getEmbedVideos(html).sort(comp);
          $scope.embedVideoUrls = items;
          return $scope.embedVideoUrl = items[0].val;
        });
      });
      $scope.$watch('springfieldEpisode', function(newValue, oldValue) {
        return getHTMLwithYQL(url4(newValue)).then(function(html) {
          return $scope.subtitle = parsers.getSubtitle(html);
        });
      });
      $scope.trustSrc = function(src) {
        return $sce.trustAsResourceUrl(src);
      };
      return $scope.position = function(x, y) {
        return "subtitle-position-" + (x.toString()) + (y.toString());
      };
    }
  ]);

}).call(this);
