// Generated by CoffeeScript 1.9.3
(function() {
  var videosubApp;

  videosubApp = angular.module('videosubApp', ['yqlService']);

  videosubApp.controller('videosubCtrl', [
    '$scope', '$http', '$sce', 'getHTMLwithYQL', function($scope, $http, $sce, getHTMLwithYQL) {
      var url;
      $scope.trustSrc = function(src) {
        return $sce.trustAsResourceUrl(src);
      };
      $scope.titleQuery = 'modern';
      url = 'http://www.springfieldspringfield.co.uk/tv_show_episode_scripts.php?search=modern';
      getHTMLwithYQL(url).then(function(htmlStr) {
        return console.log(htmlStr);
      });
      $scope.searchTitles = function() {
        getTitlesFromSpringfield($scope.titleQuery, function(items) {
          $scope.springfieldTitleSuggestions = items;
          $scope.springfieldTitle = items[0].val;
          return $scope.$apply();
        });
        return getTitlesFromTVOnline($scope.titleQuery, function(items) {
          $scope.tvonlineTitleSuggestions = items;
          $scope.tvonlineTitle = items[0].val;
          return $scope.$apply();
        });
      };
      $scope.searchEpisodes = function() {
        getEpisodesFromSpringfield($scope.springfieldTitle, function(items) {
          $scope.springfieldEpisodes = items;
          $scope.springfieldEpisode = items[0].val;
          return $scope.$apply();
        });
        return getEpisodesFromTVOnline($scope.tvonlineTitle, function(items) {
          $scope.tvonlineEpisodes = items;
          $scope.tvonlineEpisode = items[0].val;
          return $scope.$apply();
        });
      };
      $scope.showVideo = function() {
        return getEmbedVideos($scope.tvonlineEpisode, function(items) {
          $scope.embedVideoUrls = items;
          $scope.embedVideoUrl = items[0].val;
          return $scope.$apply();
        });
      };
      return $scope.showSubtitle = function() {
        return getSubtitle($scope.springfieldEpisode, function(text) {
          $scope.subtitle = text;
          return $scope.$apply();
        });
      };
    }
  ]);

}).call(this);
