// Generated by CoffeeScript 1.9.3
(function() {
  var videosubApp;

  videosubApp = angular.module('videosubApp', []);

  videosubApp.controller('videosubCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $scope.searchTitle = function() {
        getTitlesFromSpringfield($scope.titleQuery, function(items) {
          $scope.springfieldTitleSuggestions = items;
          $scope.springfieldTitle = items[0].val;
          return $scope.$apply();
        });
        return getTitlesFromTVOnline($scope.titleQuery, function(items) {
          $scope.tvonlineTitleSuggestions = items;
          $scope.tvonlineTitle = items[0].val;
          return $scope.$apply();
        });
      };
    }
  ]);

}).call(this);
