// Generated by CoffeeScript 1.9.3
(function() {
  var getCrossHTML, getTitlesFromSpringfield, getTitlesFromTVOnline, root;

  getCrossHTML = function(url, callback) {
    var yql;
    yql = "http://query.yahooapis.com/v1/public/yql?q=" + encodeURIComponent("select * from html where url='" + url + "'") + "&format=xml&callback=?";
    return $.getJSON(yql, function(data) {
      return callback(data.results[0]);
    });
  };

  getTitlesFromSpringfield = function(name, callback) {
    var url;
    url = 'http://www.springfieldspringfield.co.uk/tv_show_episode_scripts.php?search=' + encodeURIComponent(name);
    return getCrossHTML(url, function(htmlStr) {
      var html, jQitems;
      html = $.parseHTML(htmlStr);
      jQitems = $(html).find('.script-list-item').map(function() {
        var val;
        val = $(this).attr("href").match(/.*tv-show=(.*)/)[1];
        name = $(this).text();
        return {
          'val': val,
          'name': name
        };
      });
      return callback(jQitems.toArray());
    });
  };

  getTitlesFromTVOnline = function(name, callback) {
    var url;
    url = 'http://tvonline.tw/search.php?key=' + encodeURIComponent(name);
    return getCrossHTML(url, function(htmlStr) {
      var html, jQitems;
      html = $.parseHTML(htmlStr);
      jQitems = $(html).find(".found a").map(function() {
        var val;
        val = $(this).attr("href").match(/(.*)\//)[1];
        name = $(this).text();
        return {
          'val': val,
          'name': name
        };
      });
      return callback(jQitems.toArray());
    });
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.getCrossHTML = getCrossHTML;

  root.getTitlesFromSpringfield = getTitlesFromSpringfield;

  root.getTitlesFromTVOnline = getTitlesFromTVOnline;

}).call(this);
