// Generated by CoffeeScript 1.9.3
(function() {
  var parseService;

  parseService = angular.module('parseService', []);

  parseService.factory('parsers', [
    function() {
      var parsers;
      parsers = {};
      parsers.getTitlesFromSpringfield = function(html) {
        var jQitems;
        jQitems = $(html).find('.script-list-item').map(function() {
          var name, val;
          val = $(this).attr('href');
          name = $(this).text();
          return {
            'val': val,
            'name': name
          };
        });
        return jQitems.toArray();
      };
      parsers.getTitlesFromTVOnline = function(html) {
        var jQitems;
        jQitems = $(html).find('.found a').map(function() {
          var name, val;
          val = $(this).attr('href');
          name = $(this).text();
          return {
            'val': val,
            'name': name
          };
        });
        return jQitems.toArray();
      };
      parsers.getEpisodesFromSpringfield = function(html) {
        var jQitems;
        jQitems = $(html).find('.season-episode-title').map(function() {
          var e, name, s, val;
          val = $(this).attr('href');
          s = parseInt(val.match(/\&episode\=s(\d*)/)[1]).toString();
          e = parseInt(val.match(/\&episode\=s\d*e(\d*)/)[1]).toString();
          name = $(this).text().match(/\-\ (.*)$/)[1];
          return {
            'val': val,
            'name': "s" + s + " e" + e + " - " + name
          };
        });
        return jQitems.toArray();
      };
      parsers.getEpisodesFromTVOnline = function(html) {
        var jQitems;
        jQitems = $(html).find('.Season ul a').map(function() {
          var e, name, s, val;
          val = $(this).attr('href');
          s = val.match(/season-([^\-]*)-/)[1];
          e = val.match(/episode-(.*)\/$/)[1];
          name = $(this).text().match(/\-\ (.*)$/)[1];
          return {
            'val': val,
            'name': "s" + s + " e" + e + " - " + name
          };
        });
        return jQitems.toArray();
      };
      parsers.getEmbedVideos = function(html) {
        var jQitems;
        jQitems = $(html).find('#linkname_nav a').map(function() {
          var name, val;
          val = $(this).attr('onclick').match(/'(.*)'/)[1];
          name = $(this).text();
          return {
            'val': val,
            'name': name
          };
        });
        return jQitems.toArray();
      };
      parsers.getSubtitle = function(html) {
        var scripts;
        scripts = $(html).find("div.scrolling-script-container").html().split("<br>").map(function(s) {
          return "<span> " + (s.replace(/(\t|\n|\r)/gm, "").trim()) + " </span>";
        }).join("<br>");
        return scripts;
      };
      return parsers;
    }
  ]);

}).call(this);
