// Generated by CoffeeScript 1.9.3
(function() {
  var parseService;

  parseService = angular.module('parseService', []);

  parseService.factory('parsers', [
    function() {
      var parsers;
      parsers = {};
      parsers.getTitlesFromSpringfield = function(htmlStr) {
        var html, jQitems;
        html = $.parseHTML(htmlStr);
        jQitems = $(html).find('.script-list-item').map(function() {
          var name, val;
          val = $(this).attr('href').match(/.*tv-show=(.*)/)[1];
          name = $(this).text();
          return {
            'val': val,
            'name': name
          };
        });
        return jQitems.toArray();
      };
      return parsers;
    }
  ]);

}).call(this);
